import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import { Flex, Text } from "@chakra-ui/react";

import { api } from "@/utils/api";
import Header from "./components/header";
import Content from "./components/content";

const Home: React.FC = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex flexDir={"column"} align={"center"} h={"100vh"}>
        <Header />
        <Content />
      </Flex>
    </>
  );
};

export default Home;
