import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import { Button, Flex, Text } from "@chakra-ui/react";

import { api } from "@/utils/api";

const AuthShowcase: React.FC = () => {
  const { data: sessionData } = useSession();

  const { data: secretMessage } = api.example.getSecretMessage.useQuery(
    undefined, // no input
    { enabled: sessionData?.user !== undefined }
  );

  return (
    <div>
      <p>
        {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
        {secretMessage && <span> - {secretMessage}</span>}
      </p>
      <Button
        _active={{ transform: "scale(0.95)" }}
        shadow={"lg"}
        onClick={sessionData ? () => void signOut() : () => void signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </Button>
    </div>
  );
};

const Home: React.FC = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex flexDir={"column"} justify={"center"} align={"center"} h={"100vh"}>
        <Text>
          {hello.data ? hello.data.greeting : "Loading tRPC query..."}
        </Text>
        <AuthShowcase />
      </Flex>
    </>
  );
};

export default Home;
